BDIR = ./build
BINARY = clicker.exe
CC = gcc

CFLAGS = -Wall -Wextra -std=c17 -O1 -I./include
LIBS = -lm

OBJS = $(patsubst src/%.c,$(BDIR)/%.o,$(wildcard src/*.c))

all: $(BDIR) $(BINARY)

$(BINARY): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(BINARY) $(LIBS)

$(BDIR)/%.o: src/%.c | $(BDIR)
	$(CC) $(CFLAGS) -c $< -o $@

$(BDIR):
	mkdir $(BDIR)

clean:
	del /Q $(BDIR)\*.o
	del /Q $(BINARY)

.PHONY: all clean   