# GENERATED BY CLAUDE SONNET 5

#!/usr/bin/env bash
#
# dmg_maker.sh
#
# Builds a polished, "drag-to-Applications" style .dmg installer for clicker.app.
# Layout (a classic triangle arrangement inside the Finder window):
#
#         [ README.rtf ]
#     [clicker.app]     [Applications ->]
#
# Requirements: macOS 10.13+ (uses APFS disk images + modern hdiutil/osascript).
#
# Usage: ./dmg_maker.sh
# (No CLI arguments — all inputs are constants below, matching the sibling
#  files expected next to this script.)

set -euo pipefail

# ---------------------------------------------------------------------------
# Constants — inputs are files sitting next to this script, not CLI args.
# ---------------------------------------------------------------------------
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

readonly APP_NAME="clicker.app"
readonly APP_SRC="${SCRIPT_DIR}/${APP_NAME}"

readonly BACKGROUND_IMAGE_SRC="${SCRIPT_DIR}/background_image.png"
readonly BACKGROUND_IMAGE_NAME="background.png"     # name it'll have inside the dmg

readonly README_SRC="${SCRIPT_DIR}/README.rtf"
readonly README_NAME="README.rtf"

readonly VOLUME_NAME="Clicker"                       # name shown in Finder sidebar
readonly FINAL_DMG="${SCRIPT_DIR}/clicker.dmg"        # final compressed output

# Staging / scratch locations
readonly WORK_DIR="$(mktemp -d /tmp/dmg_build.XXXXXX)"
readonly STAGING_DIR="${WORK_DIR}/staging"
readonly TMP_DMG="${WORK_DIR}/tmp.dmg"

# Finder window geometry (content-area coordinates, in points)
readonly WINDOW_BOUNDS="{100, 100, 700, 500}"   # {left, top, right, bottom} -> 800x500 window
readonly ICON_SIZE=110
readonly TEXT_SIZE=13

# Icon positions {x, y} inside the window — arranged as a triangle:
#   README at the apex (top-center), app at bottom-left, Applications at bottom-right.
readonly POS_README="{320, 90}"
readonly POS_APP="{170, 230}"
readonly POS_APPLICATIONS="{450, 225}"

# ---------------------------------------------------------------------------
# Cleanup — always runs, even on failure, so we never leave a mounted volume
# or stray temp files behind.
# ---------------------------------------------------------------------------
MOUNT_POINT=""

cleanup() {
    if [[ -n "${MOUNT_POINT}" ]] && mount | grep -q "${MOUNT_POINT}"; then
        hdiutil detach "${MOUNT_POINT}" -quiet -force || true
    fi
    rm -rf "${WORK_DIR}"
}
trap cleanup EXIT

# ---------------------------------------------------------------------------
# 0. Sanity checks
# ---------------------------------------------------------------------------
for required in "${APP_SRC}" "${BACKGROUND_IMAGE_SRC}" "${README_SRC}"; do
    if [[ ! -e "${required}" ]]; then
        echo "error: required input not found: ${required}" >&2
        exit 1
    fi
done

if [[ -e "${FINAL_DMG}" ]]; then
    echo "Removing existing ${FINAL_DMG}..."
    rm -f "${FINAL_DMG}"
fi

echo "==> Staging contents in ${STAGING_DIR}"
mkdir -p "${STAGING_DIR}"

# ---------------------------------------------------------------------------
# 1. Copy inputs into the staging folder that becomes the dmg's contents.
#    `ditto` (rather than cp -R) preserves the .app bundle structure,
#    extended attributes, and resource forks correctly.
# ---------------------------------------------------------------------------
ditto "${APP_SRC}" "${STAGING_DIR}/${APP_NAME}"
ditto "${README_SRC}" "${STAGING_DIR}/${README_NAME}"

# The background image is hidden inside a ".background" folder, which is the
# Finder convention — it keeps the image out of the visible file listing.
mkdir -p "${STAGING_DIR}/.background"
ditto "${BACKGROUND_IMAGE_SRC}" "${STAGING_DIR}/.background/${BACKGROUND_IMAGE_NAME}"

# Symlink to /Applications, so users can drag the app straight in.
ln -s /Applications "${STAGING_DIR}/Applications"

# ---------------------------------------------------------------------------
# 2. Build a read/write staging disk image (APFS — modern default filesystem)
#    sized to comfortably fit the staged contents.
# ---------------------------------------------------------------------------
STAGED_SIZE_MB=$(du -sm "${STAGING_DIR}" | cut -f1)
DMG_SIZE_MB=$(( STAGED_SIZE_MB + 50 ))   # generous padding for filesystem overhead

echo "==> Creating temporary read/write image (${DMG_SIZE_MB}MB)"
hdiutil create \
    -volname "${VOLUME_NAME}" \
    -srcfolder "${STAGING_DIR}" \
    -fs APFS \
    -format UDRW \
    -size "${DMG_SIZE_MB}m" \
    -ov \
    -quiet \
    "${TMP_DMG}"

# ---------------------------------------------------------------------------
# 3. Mount it read/write so Finder can style it.
# ---------------------------------------------------------------------------
echo "==> Mounting temporary image"
MOUNT_POINT=$(hdiutil attach "${TMP_DMG}" -readwrite -noverify -noautoopen \
    | grep '/Volumes/' \
    | awk -F'\t' '{print $NF}' \
    | xargs)

if [[ -z "${MOUNT_POINT}" ]]; then
    echo "error: could not determine mount point" >&2
    exit 1
fi
echo "    mounted at ${MOUNT_POINT}"

# ---------------------------------------------------------------------------
# 4. Style the Finder window via AppleScript: icon view, background image,
#    window size/position, icon size, and the triangle layout.
# ---------------------------------------------------------------------------
echo "==> Styling Finder window"
osascript <<APPLESCRIPT
tell application "Finder"
    tell disk "${VOLUME_NAME}"
        open

        set current view of container window to icon view
        set toolbar visible of container window to false
        set statusbar visible of container window to false
        set the bounds of container window to ${WINDOW_BOUNDS}

        set theViewOptions to the icon view options of container window
        set arrangement of theViewOptions to not arranged
        set icon size of theViewOptions to ${ICON_SIZE}
        set text size of theViewOptions to ${TEXT_SIZE}
        set background picture of theViewOptions to file ".background:${BACKGROUND_IMAGE_NAME}"

        -- Position each item to form the triangle layout.
        set position of item "${README_NAME}" of container window to ${POS_README}
        set position of item "${APP_NAME}" of container window to ${POS_APP}
        set position of item "Applications" of container window to ${POS_APPLICATIONS}

        -- Force a redraw and let Finder flush window state to .DS_Store.
        close
        open
        update without registering applications
        delay 1
    end tell
end tell
APPLESCRIPT

# ---------------------------------------------------------------------------
# 5. Unmount before converting to the final compressed, read-only image.
# ---------------------------------------------------------------------------
echo "==> Unmounting"
hdiutil detach "${MOUNT_POINT}" -quiet
MOUNT_POINT=""   # already detached; skip cleanup's detach step

# ---------------------------------------------------------------------------
# 6. Convert to a compressed, read-only dmg — the format end users receive.
# ---------------------------------------------------------------------------
echo "==> Converting to compressed read-only image"
hdiutil convert "${TMP_DMG}" \
    -format UDZO \
    -imagekey zlib-level=9 \
    -o "${FINAL_DMG}" \
    -quiet

echo "==> Done: ${FINAL_DMG}"